#######################################
##         Server Settings           ##
#######################################
server:
  motd:
    enabled: true
    content: "&7Server is running &b&lNeptune Core &7by &fLumina Games"
  player-hover:
    enabled: true
    content:
      - "&bNeptune Core :)"
      - "You can customize this too!"


#######################################
##         Fallback Servers          ##
#######################################

# These servers will also be used for /hub command
lobby-servers:
  - lobby
# If a server goes offline or crashes it will send players to the lobby servers
fallback: true
# The plugin will still connect the player to the fallback server if it is full
# You can give VIP or Staff neptune.fallback.bypass permission to bypass this if wanted
respect-limit: false
# If the kick message contains the following words it will not send the player to
# the fallback servers
ignored-reasons:
  - "ban"
  - "kick"
  - "blacklist"
  - "maintenance"
ignored-servers:
  - bedwars
  - skywars
  - lifesteal


#######################################
##         Server Maintenance        ##
#######################################

maintenance:
  enabled: false
  kick-message:
    - '&cThe server is currently under maintenance'
    - '&fPlease join back later'